version: '3.3'

services:
  buzz:
    build: .
    command: python script.py --topic "/rf/#"
    volumes:
      - ./gpio.py:/app/script.py
    devices:
      - /dev/gpiomem
  buzz_ha:
    image: danobot/buzz
    container_name: buzz_ha
    environment:
      MQTT_TOPIC: "/buzz"
      MQTT_HOST: "10.1.1.130"
      # GPIO_PIN: 18
      # BUZZER_REPS: 1
      # BUZZER_PAUSE: 1
      # BUZZER_LENGTH: 20
      # BUZZER_COUNT: 1
    devices:
      - /dev/gpiomem
