version: '3.3'
services:
  audio-buzzer-rpi-ha:
    build: .
    image: audio-buzzer-rpi-ha
    container_name: audio-buzzer-rpi-ha
    restart: unless-stopped
    volumes:
      - /opt/homeassistant/apps:/config:ro
    devices:
      - /dev/gpiomem
